name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Build Tag'
        required: true
        type: string
      runTests:
        description: 'Run tests'
        required: true
        default: true 
        type: boolean        
      sendSlackNotification:
        description: 'Send Slack Notification'
        required: true
        default: true 
        type: boolean

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: |
        echo "MY_SECRET" ${{ secrets.MY_SECRET }}
        sbt test
